export enum EmployeePerformanceStatus {
  NOT_STARTED = 'NOT_STARTED',
  DRAFT = 'DRAFT',
  SUBMITTED = 'SUBMITTED',
  UNDER_REVIEW = 'UNDER_REVIEW',
  REVIEWED = 'REVIEWED',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
}

export enum LearningGoalsEnum {
  UPSKILL_TECHNICAL = 'UPSKILL_TECHNICAL',
  LEADERSHIP_MANAGEMENT = 'LEADERSHIP_MANAGEMENT',
  CERTIFICATION_ACHIEVED = 'CERTIFICATION_ACHIEVED',
  PROCESS_IMPROVEMENT = 'PROCESS_IMPROVEMENT',
  CROSS_FUNCTIONAL_KNOWLEDGE = 'CROSS_FUNCTIONAL_KNOWLEDGE',
  ON_TRACK = 'ON_TRACK',
  NEEDS_GUIDANCE = 'NEEDS_GUIDANCE',
}

export enum FeedbackOnWorkCultureEnum {
  EXCELLENT = 'EXCELLENT',
  VERY_GOOD = 'VERY_GOOD',
  POSITIVE = 'POSITIVE',
  NEUTRAL = 'NEUTRAL',
  NEEDS_IMPROVEMENT = 'NEEDS_IMPROVEMENT',
}

export enum WorkLifeBalanceEnum {
  EXCELLENT = 'EXCELLENT',
  GOOD = 'GOOD',
  MANAGEABLE = 'MANAGEABLE',
  STRESSFUL = 'STRESSFUL',
  NEEDS_ATTENTION = 'NEEDS_ATTENTION',
}

export enum SuggestionsForImprovementEnum {
  PROCESS_AUTOMATION = 'PROCESS_AUTOMATION',
  TRAINING_WORKSHOPS = 'TRAINING_WORKSHOPS',
  BETTER_TOOLING = 'BETTER_TOOLING',
  RESOURCE_ALLOCATION = 'RESOURCE_ALLOCATION',
  CROSS_TEAM_SYNC = 'CROSS_TEAM_SYNC',
  NONE = 'NONE',
}

export enum RateCompanyEnvironmentEnum {
  FIVE_STAR = 'FIVE_STAR',
  FOUR_STAR = 'FOUR_STAR',
  THREE_STAR = 'THREE_STAR',
  TWO_STAR = 'TWO_STAR',
  ONE_STAR = 'ONE_STAR',
}
