export enum ReviewEmployeeType {
  EMPLOYEE = 'EMPLOYEE',
  INTERN = 'INTERN',
  MANAGER = 'MANAGER',
}

export enum ReviewAssignedBy {
  MANAGER = 'MANAGER',
  EMPLOYEE = 'EMPLOYEE',
  INTERN = 'INTERN',
  ADMIN = 'ADMIN',
}

export enum QuarterlyReviewStatus {
  NOT_STARTED = 'NOT_STARTED',
  DRAFT = 'DRAFT',
  PENDING = 'PENDING',
  IN_PROGRESS = 'IN_PROGRESS',
  SUBMITTED = 'SUBMITTED',
  UNDER_REVIEW = 'UNDER_REVIEW',
  REVIEWED = 'REVIEWED',
  COMPLETED = 'COMPLETED',
  REJECTED = 'REJECTED',
}
export const QuaterlyReviewStatus = QuarterlyReviewStatus;
export type QuaterlyReviewStatus = QuarterlyReviewStatus;

export { QuaterlyEnum, QuarterlyEnum } from '../../master/enums/quaterly.enums';

export enum PerformanceStrengthsEnum {
  TECHNICAL_EXCELLENCE = 'TECHNICAL_EXCELLENCE',
  CONSISTENT_DELIVERY = 'CONSISTENT_DELIVERY',
  LEADERSHIP_INITIATIVE = 'LEADERSHIP_INITIATIVE',
  STRONG_COMMUNICATION = 'STRONG_COMMUNICATION',
  PROBLEM_SOLVING = 'PROBLEM_SOLVING',
  TEAM_PLAYER = 'TEAM_PLAYER',
  FAST_LEARNER = 'FAST_LEARNER',
  EXCEPTIONAL = 'EXCEPTIONAL',
  GOOD = 'GOOD',
}

export enum AreasOfImprovementEnum {
  TIME_MANAGEMENT = 'TIME_MANAGEMENT',
  TECHNICAL_SKILLS = 'TECHNICAL_SKILLS',
  COMMUNICATION = 'COMMUNICATION',
  ATTENTION_TO_DETAIL = 'ATTENTION_TO_DETAIL',
  OWNERSHIP = 'OWNERSHIP',
  DOCUMENTATION = 'DOCUMENTATION',
  NEEDS_IMPROVEMENT = 'NEEDS_IMPROVEMENT',
  NONE = 'NONE',
}

export enum AdditionalRemarksEnum {
  EXCEEDS_EXPECTATIONS = 'EXCEEDS_EXPECTATIONS',
  MEETS_EXPECTATIONS = 'MEETS_EXPECTATIONS',
  NEEDS_IMPROVEMENT = 'NEEDS_IMPROVEMENT',
  OUTSTANDING_PERFORMANCE = 'OUTSTANDING_PERFORMANCE',
  SATISFACTORY = 'SATISFACTORY',
  UNSATISFACTORY = 'UNSATISFACTORY',
}

export enum RatingScaleEnum {
  UNSATISFACTORY = 1,
  NEEDS_IMPROVEMENT = 2,
  MEETS_EXPECTATIONS = 3,
  EXCEEDS_EXPECTATIONS = 4,
  OUTSTANDING = 5,
}

export const RATING_DESCRIPTIONS: Record<number, string> = {
  1: 'Unsatisfactory',
  2: 'Needs Improvement',
  3: 'Meets Expectations',
  4: 'Exceeds Expectations',
  5: 'Outstanding',
};
