export enum ReviewEmployeeType {
  EMPLOYEE = 'EMPLOYEE',
  INTERN = 'INTERN',
  MANAGER = 'MANAGER',
}

export enum ReviewAssignedBy {
  MANAGER = 'MANAGER',
  EMPLOYEE = 'EMPLOYEE',
  INTERN = 'INTERN',
  ADMIN = 'ADMIN',
}

export enum QuarterlyReviewStatus {
  NOT_STARTED = 'NOT_STARTED',
  DRAFT = 'DRAFT',
  PENDING = 'PENDING',
  IN_PROGRESS = 'IN_PROGRESS',
  SUBMITTED = 'SUBMITTED',
  UNDER_REVIEW = 'UNDER_REVIEW',
  REVIEWED = 'REVIEWED',
  COMPLETED = 'COMPLETED',
  REJECTED = 'REJECTED',
  APPROVED = 'APPROVED',
  EDIT_REQUESTED = 'EDIT_REQUESTED',
  EDIT_GRANTED = 'EDIT_GRANTED',
  ASSIGNED = 'ASSIGNED',
  PERFORMANCE_RECEIVED = 'PERFORMANCE_RECEIVED',
  REQUESTED_FOR_EDIT = 'REQUESTED_FOR_EDIT',
  APPROVED_FOR_EDITING = 'APPROVED_FOR_EDITING',
  RE_SUBMITTED = 'RE_SUBMITTED',
  NOT_UPDATED = 'NOT_UPDATED',
  ALLOWED_TO_EDIT = 'ALLOWED_TO_EDIT',
}
export const QuaterlyReviewStatus = QuarterlyReviewStatus;
export type QuaterlyReviewStatus = QuarterlyReviewStatus;

export { QuaterlyEnum, QuarterlyEnum } from '../../master/enums/quaterly.enums';

export enum PerformanceStrengthsEnum {
  TECHNICAL_EXCELLENCE = 'TECHNICAL_EXCELLENCE',
  CONSISTENT_DELIVERY = 'CONSISTENT_DELIVERY',
  LEADERSHIP_INITIATIVE = 'LEADERSHIP_INITIATIVE',
  STRONG_COMMUNICATION = 'STRONG_COMMUNICATION',
  PROBLEM_SOLVING = 'PROBLEM_SOLVING',
  TEAM_PLAYER = 'TEAM_PLAYER',
  FAST_LEARNER = 'FAST_LEARNER',
  EXCEPTIONAL = 'EXCEPTIONAL',
  GOOD = 'GOOD',
}

export enum AreasOfImprovementEnum {
  TIME_MANAGEMENT = 'TIME_MANAGEMENT',
  TECHNICAL_SKILLS = 'TECHNICAL_SKILLS',
  COMMUNICATION = 'COMMUNICATION',
  ATTENTION_TO_DETAIL = 'ATTENTION_TO_DETAIL',
  OWNERSHIP = 'OWNERSHIP',
  DOCUMENTATION = 'DOCUMENTATION',
  NEEDS_IMPROVEMENT = 'NEEDS_IMPROVEMENT',
  NONE = 'NONE',
}

export enum AdditionalRemarksEnum {
  EXCEEDS_EXPECTATIONS = 'EXCEEDS_EXPECTATIONS',
  MEETS_EXPECTATIONS = 'MEETS_EXPECTATIONS',
  NEEDS_IMPROVEMENT = 'NEEDS_IMPROVEMENT',
  OUTSTANDING_PERFORMANCE = 'OUTSTANDING_PERFORMANCE',
  SATISFACTORY = 'SATISFACTORY',
  UNSATISFACTORY = 'UNSATISFACTORY',
}

export enum RatingVisibilityStatus {
  RATED = 'RATED',
  PENDING_REVIEW = 'PENDING_REVIEW',
}

export enum AppraisalNoticeType {
  QUARTER_ASSIGNED = 'APPRAISAL_QUARTER_ASSIGNED',
  SUBMISSION_CONFIRMED = 'APPRAISAL_SUBMISSION_CONFIRMED',
  SUBMISSION_RECEIVED = 'APPRAISAL_SUBMISSION_RECEIVED',
  EDIT_REQUESTED = 'APPRAISAL_EDIT_REQUESTED',
  EDIT_GRANTED = 'APPRAISAL_EDIT_GRANTED',
  REVIEW_COMPLETED = 'APPRAISAL_REVIEW_COMPLETED',
  DEADLINE_REMINDER = 'APPRAISAL_DEADLINE_REMINDER',
}

export enum RatingScaleEnum {
  UNSATISFACTORY = 1,
  NEEDS_IMPROVEMENT = 2,
  MEETS_EXPECTATIONS = 3,
  EXCEEDS_EXPECTATIONS = 4,
  OUTSTANDING = 5,
}

export const RATING_DESCRIPTIONS: Record<number, string> = {
  1: 'Unsatisfactory',
  2: 'Needs Improvement',
  3: 'Meets Expectations',
  4: 'Exceeds Expectations',
  5: 'Outstanding',
};
