export enum WorkLocation {
  WORK_FROM_HOME = 'Work From Home',
  WFH = 'WFH',
  CLIENT_VISIT = 'Client Visit',
  OFFICE = 'Office',
  PRESENT = 'Present',
  LEAVE = 'Leave',
  COMP_OFF_LEAVE = 'Comp-Off Leave',
  NOT_UPDATED = 'Not Updated',
  UPCOMING = 'Upcoming',
  HOLIDAY = 'Holiday',
  CV = 'CV',
  ABSENT = 'Absent',
  WEEKEND = 'Weekend',
}

export enum WorkLocationKeyword {
  WFH = 'wfh',
  WORK_FROM_HOME = 'work from home',
  CLIENT_VISIT = 'client visit',
  OFFICE = 'office',
  PRESENT = 'present',
  LEAVE = 'leave',
  COMP_OFF_LEAVE = 'comp-off leave',
  NOT_UPDATED = 'not updated',
  UPCOMING = 'upcoming',
  HOLIDAY = 'holiday',
  CV = 'cv',
  APPLY_LEAVE = 'apply leave',
  HALF_DAY_LEAVE = 'half day leave',
  HALF_DAY = 'half day',
  ABSENT = 'absent',
  WEEKEND = 'weekend',
}
